//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Menu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Menu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description present.
        /// </summary>
        internal static string DelegateMenuOption_GetDescriptionFromOptionCodeDelegate_NoDescription {
            get {
                return ResourceManager.GetString("DelegateMenuOption_GetDescriptionFromOptionCodeDelegate_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue or [ESC] to quit....
        /// </summary>
        internal static string MenuCollection_PromptToContinue_ContinueOrQuit {
            get {
                return ResourceManager.GetString("MenuCollection_PromptToContinue_ContinueOrQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; Select option or [ESC] to quit....
        /// </summary>
        internal static string MenuCollection_WriteMenuFooter_SelectOptionOrQuit {
            get {
                return ResourceManager.GetString("MenuCollection_WriteMenuFooter_SelectOptionOrQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] {1}.
        /// </summary>
        internal static string MenuCollection_WriteMenuOption {
            get {
                return ResourceManager.GetString("MenuCollection_WriteMenuOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception type {0} was thrown..
        /// </summary>
        internal static string MenuOption_ShowExceptionDetails_ExceptionType {
            get {
                return ResourceManager.GetString("MenuOption_ShowExceptionDetails_ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner Exception: {0}.
        /// </summary>
        internal static string MenuOption_ShowExceptionDetails_InnerException {
            get {
                return ResourceManager.GetString("MenuOption_ShowExceptionDetails_InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message: &apos;{0}&apos;.
        /// </summary>
        internal static string MenuOption_ShowExceptionDetails_Message {
            get {
                return ResourceManager.GetString("MenuOption_ShowExceptionDetails_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Inner Exception.
        /// </summary>
        internal static string MenuOption_ShowExceptionDetails_NoInnerException {
            get {
                return ResourceManager.GetString("MenuOption_ShowExceptionDetails_NoInnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: &apos;{0}&apos;.
        /// </summary>
        internal static string MenuOption_ShowExceptionDetails_Source {
            get {
                return ResourceManager.GetString("MenuOption_ShowExceptionDetails_Source", resourceCulture);
            }
        }
    }
}
